### ISSUE TITLE
Layer Renderer

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-scripts#1]
The [ATT&CK Navigator](https://github.com/mitre-attack/attack-navigator) defines a layer format which can be used to describe annotations on ATT&CK matrixes in JSON format. The principal functionality of the ATT&CK Navigator is viewing and editing these matrixes, but it also includes an export functionality to render and save the matrix to an SVG image. Unfortunately, the layer renderer is only available through the webapp UI and therefore unsuited for many use cases involving programmatic layer generation.

This issue proposes the creation of a layer renderer script. It would take as input a layer file and optional parameters for the output file destination and format, dimensions, fields to display in the header, and so on. The script would exist as a python function for importing into larger workflows, and would include a CLI. The script would be implemented in python3.

**Comment by wbooth** [comment]
This would be really cool to have as a function call and then to add an API route for it. Using the mitre-attack.github.io instance to auto render svgs from layer files could open up some interesting use cases.

**Comment by isaisabel** [comment]
Completed in #41.
