### ISSUE TITLE
diff_stix: detailed changes

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-scripts#11]
As a user of ATT&CK and the diff_stix script, I want to be able to see granular details about what changed for each object in an update.

Add a --detailed-changes flag which reports on which fields have changed between updates (though not the contents of those changes). It should also report on whether or not relationships have been added, changed, and removed.

**Comment by jondricek** [comment]
Admin note: closing all remaining issues and pull requests prior to archiving the repository
