### ISSUE TITLE
Layer Operations

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-scripts#2]
The ATT&CK Navigator defines a layer format which can be used to describe annotations on ATT&CK matrixes in JSON format. The principal functionality of the ATT&CK Navigator is viewing and editing these matrixes, but it also includes the ability to merge (combine) the annotations from multiple layers. Unfortunately, these layer operations are only available in the GUI and therefore unsuited to scripting.

This issue proposes the creation of a layer-operations script to handling merging of layer annotations. It would allow complex manipulations of scores, comments, enabled/disabled states, colors, and metadata.

The script would feature two interfaces, and evaluation of the technique annotations would be performed by passing functions as named arguments.

## list interface
In this interface, the layers would be provided in a list. The annotation-evaluation function would then be passed a list of that annotation in the same order as the layers specified. For example, to average the scores of three layers:
```python
avglayer = layerops([layer1, layer2, layer3], score=lambda t: sum(t)/len(t))
```
To double the score of a single input layer:
```python
doublelayer = layerops([layer1], score=lambda t: t[0] * 2)
```
To combine the comments of three layers:
```python
commentlayer = layerops([layer1, layer2, layer3], comment=lambda t: ", ".join(t))
```

Another example where both score and enabled are set
```python
layer = layerops([layer1, layer2], score=lambda t: t[0] * t[1], enabled=lambda t: t[0] or t[1])
```

## dict interface
In the case where the user is working with complex formulas, remembering the index of a layer may be difficult. In this case, the user could provide a dict of layers as input. The input to the annotation-evaluation function would therefore also be a dict:

```python
layer = layerops({a: layer1, b: layer2, c: layer3}, score=lambda t: (t["a"] + t["b"]) / t["c"])
```

```python
layer = layerops({a: layer1, b: layer2}, comment=lambda t: "comment for layer1 is {a}, comment for layer2 is {b}".replace("{a}", t["a"]).replace("{b}", t["b"]))
```

**Comment by isaisabel** [comment]
WIP in #15

**Comment by beerMT** [comment]
Looking forward to this!

**Comment by isaisabel** [comment]
@beerMT this script is now released on the master branch.
