### ISSUE TITLE
typo in scripts/README.md and CHANGELOG.md

### ISSUE THREAD

**Issue by trankmichael** [mitre-attack/attack-scripts#7]
Really small issue, currently the first script link is broken. 

`techniques_from_data_src.py` should actually be `techniques_from_data_source.py`.

The redirect goes to https://github.com/mitre-attack/attack-scripts/blob/master/scripts/techniques_from_data_src.py

**Comment by isaisabel** [comment]
I've fixed the typo. Thank you for pointing this out!
