### ISSUE TITLE
Data sources support in diff_stix

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-scripts#70]
As a user of diff_stix, I want the script to be able to summarize changes in [data sources and data components](https://github.com/mitre-attack/attack-datasources).

Update diff_stix to include data sources and data components. Data components should be nested beneath their data sources using the same logic as sub-techniques and techniques.

**Comment by jondricek** [comment]
Admin note: closing all remaining issues and pull requests prior to archiving the repository
