### ISSUE TITLE
Track contributor changes in diff_stix

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-scripts#71]
As a maintainer of ATT&CK release notes, I want to be able to determine who contributed to the most recent release of ATT&CK using diff_stix.

Note: this is not simply subtracting the set of contributors on the old version from the new. A contributor listing who existed on an object before, but also was added to a new/updated object, should be considered an addition for the sake of the output of this comparison since they contributed to content added/updated in the new version.

Track changes to contributors on an object-by-object basis. The following characteristics constitute a contributor to a release:
- Contributors who were not previously present on a given object which has been updated in any way
- Anyone who contributed to a new object

The following characteristics DO NOT constitute a contributor for a release:
- If the order of contributors on an object are changed
- If a contributor is removed from an object and (not re-added on a different object)

---

- [ ] The markdown report should include a section, `contributors`, which lists the contributors to the release in a bullet-point list.
- [ ] detected contributor changes should be available on the `DiffStix` object in a field after data has been parsed.
- [ ] An argument should be given to opt-in to listing contributors in the output markdown. If the argument is not specified, the contributor data should still be parsed but not written in the markdown report.

**Comment by jondricek** [comment]
Admin note: closing all remaining issues and pull requests prior to archiving the repository
