### ISSUE TITLE
Add a table of contents to diff_stix's markdown output

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/attack-scripts#73]
As a user, I want to be able to access a table of contents for the diff_stix's Markdown output because the output can be very long. 

- [ ] The TOC should include anchor links to scroll to the relevant sections.
- [ ] The TOC should adapt to differing contents of the markdown sections, so if the user builds with `--contributors` it shows up properly
- [ ] The TOC should be opt-in through a flag (like `--contributors`)

**Comment by jondricek** [comment]
Admin note: closing all remaining issues and pull requests prior to archiving the repository
