### ISSUE TITLE
Full Mitigations Data Dump

### ISSUE THREAD

**Issue by ajread4** [mitre-attack/attack-scripts#75]
I forked this repository and added the capability to dump all mitigations for each technique and sub-technique. If the technique/sub-technique does not have one listed, I just populate with "No Mitigation". 

If I put in a PR, is there any interest? The main use case for me was for data science and generating statistics for each technique, sub-technique, and mitigation. 

Thank you!

**Comment by jondricek** [comment]
Thank you for adding that functionality! We are focusing on the [mitre-attack/mitreattack-python](https://github.com/mitre-attack/mitreattack-python) repo in place of this one so we only have to maintain one git repo of Python code. You may be interested in checking out what we've done with [mitreattack/stix20/MitreAttackData.py](https://github.com/mitre-attack/mitreattack-python/blob/master/mitreattack/stix20/MitreAttackData.py) and the examples in the [examples folder](https://github.com/mitre-attack/mitreattack-python/tree/master/examples).

Admin note: closing all remaining issues and pull requests prior to archiving the repository
