### ISSUE TITLE
[Errno 61] Connection refused

### ISSUE THREAD

**Issue by spitzd** [mitre-attack/attack-scripts#76]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cti-taxii.mitre.org', port=443): Max retries exceeded with url: /stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1042280a0>: Failed to establish a new connection: [Errno 61] Connection refused'))

Just want to check if these scripts are still being maintained?

**Comment by jondricek** [comment]
Thank you for writing in with this request. The TAXII server should be back online with an updated SSL certificate.

This repository is under consideration for being archived and/or merged with the https://github.com/mitre-attack/mitreattack-python repository. This will likely be done in the next month or two.
